### ISSUE TITLE
Did you also perform tests on other RNN models?

### ISSUE THREAD

**Issue by lars-nieradzik** [okojoalg/sequencer#7]
Hello, thank you for the interesting paper. I am wondering whether you also tried GRUs or regular RNNs? Were LSTMs always better than the other RNN models?

**Comment by okojoalg** [comment]
Hello, thank you for your question.  We will add the results that are helpful to your question to our paper soon.

**Comment by lars-nieradzik** [comment]
Then I will wait for the update of the paper. Thank you for the quick reply.
